steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/one-off-cloud-run', '.']

  - name: 'gcr.io/cloudshell-images/custom-image-validation'
    args: ['image_test.py', '--image', 'gcr.io/$PROJECT_ID/one-off-cloud-run']

images: ['gcr.io/$PROJECT_ID/one-off-cloud-run']
timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_8'
