steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args: ['build', '--builder=gcr.io/buildpacks/builder:v1', '--run-image=ghcr.io/jamesward/gcloud-buildpack-run', '--publish', 'gcr.io/$PROJECT_ID/one-off-cloud-run']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/one-off-cloud-run-cloudshell', '.']

  - name: 'gcr.io/cloudshell-images/custom-image-validation'
    args: ['image_test.py', '--image', 'gcr.io/$PROJECT_ID/one-off-cloud-run-cloudshell']

images: ['gcr.io/$PROJECT_ID/one-off-cloud-run-cloudshell']
timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_8'
